### ISSUE TITLE
support multiple uber webapps talking to the same DB

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#581]
August 2017 update: I wrote this issue in 2014 when this was a 'nice to have' thing but not really needed.  The new reality is we pretty much are going to require parallel frontend support to deal with the load, either in the form of multiple python processes on a multi-core box (damn you python GIL), and/or multiple boxes running multiple python processes with a load balancer out front.

here's a list of items that we may need to fix/modify/rewrite/test in order to make sure all of this works:
- [ ] https://github.com/magfest/ubersystem/issues/1748 session data moved into database
- [ ] kill c.BADGE_LOCK, probably, and replace with stored proc or just let our internal transactions deal with it
- [ ] create better solution for some places where we are storing files on the local filesystem (MIVS, bands, etc) https://github.com/magfest/bands/issues/4
- [ ] need to figure out architecture for load balancing on backends and how that actually works
- [ ] how will deploys will actually work, including DB migrations
- [ ] break out background daemon threads (particularly automated emails) into their own processes, we don't want them running on every backend daemon
- [ ] consider multiple python processes per box in addition to multiple boxes
- [ ] figure out where the socket errors were coming from in 2017 and how to tune servers to avoid them
- [ ] might be fine but: public-facing schedule.py page does a cache on local disk (this might be now obsoleted by our nginx caching entirely and could be removed). see ```@cached``` decorator

maybe things to think about:
- [ ] https://github.com/magfest/ubersystem/issues/2348 store unpaid attendees in DB and not session
- [ ] https://github.com/magfest/ubersystem/issues/614 might make some config changes easier with multiple backends

----
original text below
----

This is not a short-term need but eventually, we should support multiple web apps running on different servers talking to a DB on a different server.  This would let us do stuff like high-availability in case of hardware failure, load balancing, and support more robust DB replication.

In _theory_ sqlalchemy may already do the heavy lifting here.

In practice this would need a lot of testing and thought put into it.

The one thing I can think of off the top of my head is we will probably have to revisit the concept of BADGE_LOCK (which I'm not super-familiar with) and maybe re-implement that as a database transaction instead so the locking logic is done on the database, not the client.

I'm not sure what other stuff would be lurking around.

**Comment by cliffmeyers** [comment]
Greetings, 5 year MAGFest attendee and random software engineer here. I was reading this ticket and #1462. I'm curious to learn more about `BADGE_LOCK` and what the badge numbering requirements are. Someone mentioned renumbering... just curious what your use cases are. Do badge number need to be a gapless sequence?

**Comment by kitsuta** [comment]
Hi @cliffmeyers, welcome! We're kind of all still scrambling to fix up things from the prereg rush, but for a quick answer, we've historically wanted admins to be able to assign any number to a pre-assigned badge and have any badges 'shift' around it. The badge lock was a """temporary""" stopgap to prevent collision while updating thousands of badges' numbers. It... needs replacing. :)

**Comment by cliffmeyers** [comment]
@kitsuta thanks for the reply. Just curious what the use cases are for re-numbering badges? You want people in a group to have consecutive badge numbers? Are the badge numbers also used by staff and you want to keep them in a certain range? As a MAGFest attendee, I don't even recall seeing a number on my badge, or it being referenced in any way, so there must be a lot of behind-the-scenes stuff I'm not aware of.

I'm happy to leave some notes on this ticket with some implementation ideas, just want to understand the requirements better. Also if there's a link handy to the current schema I'd be curious to take a look.

**Comment by binary1230** [comment]
hey, welcome @cliffmeyers 

we have a couple use cases for badge numbering, one is it's just an easy way to lookup someone's info in the database since on checkin, we associate the badge# with the attendee record.  handy for security stuff, checking things in and out of the LAN room, if a badge is put in or out of circulation / re-issued / revoked / etc.

I think @RobRuana just did an analysis that finds that, given what we're already doing with DB transactions, c.BADGE_LOCK might not actually be really protecting us from anything and we may be able to just remove it and rely on the DB for this type of thing.

**Comment by cliffmeyers** [comment]
@binary1230 as long as the badge renumbering is done inside of a transaction (e.g. `BEGIN`), pgsql will use the `READ COMMITTED` isolation level by default, see here: https://www.postgresql.org/docs/9.1/static/transaction-iso.html   I think you're right in that should be sufficient protection unless there is a ton of DB activity going in during a renumbering operation. You can get more conservative using an explicit `LOCK` on the table with different lock modes.  https://www.postgresql.org/docs/9.1/static/explicit-locking.html

**Comment by binary1230** [comment]
cool, also I made a checklist at the top of this issue with the stuff I am aware of that we would need to pay attention to for moving to multiple backends

**Comment by binary1230** [comment]
one other very cool thing, Digitalocean (where we currently host) has a nice feature where one IP can be used to load balance onto multiple different boxes, without us having to do anything. might be worth investigating
